markdown: kramdown
title: Base Project
author: Vera Nicolás A.
baseurl: /Instituto-Centenarios/
description: Base Branding Project
keywords: Base, Branding, Project
exclude: ['README.md']
sass:
    sass_dir: _sass
    style: compressed

collections:
  videos-cortometrajes:
  videos-videopoemas:
  videos-patrioticos:
  videos-expositivos:
  videos-noticiero:
