markdown: kramdown
title: Instituto Centenarios Web
author: Vera Nicolás A.
baseurl:
description: Base Branding Project
keywords: Base, Branding, Project
exclude: ['README.md']
sass:
    sass_dir: _sass
    style: compressed

collections:
  videos-cortometrajes:
  videos-videopoemas:
  videos-patrioticos:
  videos-expositivos:
  videos-noticiero:
  latest-news:
months:
  - Enero
  - Febrero
  - Marzo
  - Abril
  - Mayo
  - Junio
  - Julio
  - Agosto
  - Septiembre
  - Octubre
  - Noviembre
  - Diciembre
